name: Deploy Static JS Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.set-url.outputs.PAGE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        id: deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      # Опционально: вычисляем URL страницы
      - name: Set page URL
        id: set-url
        run: |
          echo "PAGE_URL=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_OUTPUT

  lighthouse:
    name: 🚀 Lighthouse CI
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v0.14.0
        with:
          # берём URL из предыдущей задачи
          urls: ${{ needs.build-and-deploy.outputs.url }}
          # или перечислите конкретно:
          # urls: |
          #   https://ваш_логин.github.io/animation_test_js/
          #   https://ваш_логин.github.io/animation_test_js/js.html
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
