steps:
  - uses: actions/checkout@v4

  - uses: actions/setup-node@v4
    with:
      node-version: 20

  - name: Install & build
    run: |
      npm ci
      npm run build

  # Отладка ─ покажет, что .lighthouserc.js лежит рядом
  - run: ls -la

  - name: Serve dist
    run: |
      npx http-server ./dist -p 8080 &
      sleep 7

  - name: Run Lighthouse CI
    env:
      LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
    run: npx lhci autorun # без --config

  - name: Upload reports
    if: always()
    uses: actions/upload-artifact@v4
    with:
      name: lhci-reports
      path: lhci-reports/**
