# .github/workflows/deploy.yml

name: Build & Deploy to GitHub Pages

# Триггер: при пуше в ветку main
on:
  push:
    branches:
      - main

permissions:
  contents: read # чтобы выполнить checkout
  pages: write # чтобы публиковать в GitHub Pages
  id-token: write # нужно для authenticate-pages

jobs:
  build:
    name: 🛠 Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        # В результате в папке ./dist будут готовые статические файлы

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    name: 🚀 Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Publish to GitHub Pages
        uses: actions/publish-pages@v1
