- name: Build project # чтобы dist уже существовал
  run: npm run build

- name: Start preview server # 8080, как в конфиге
  run: |
    npm i -g http-server
    http-server ./dist -p 8080 &
    sleep 5

- name: Run Lighthouse CI
  env:
    LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }} # нужен только для target=lhci
  run: lhci autorun

- name: Upload reports # путь совпадает с outputDir
  uses: actions/upload-artifact@v4
  with:
    name: lhci-reports
    path: lhci-reports/**
