name: Lighthouse CI Audit

on:
  push:
    branches: [main]

jobs:
  lighthouseci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build & start preview server # если сборки нет — оставьте только server
        run: |
          # npm run build
          npm i -g http-server
          http-server ./dist -p 8080 &
          sleep 5

      - name: Install Lighthouse CI
        run: npm i -g @lhci/cli@0.14.x

      - name: Run Lighthouse CI
        env:
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }} # ← передаём секрет
        run: lhci autorun

      # (необязательно) складываем html/json в artifacts
      - name: Upload Lighthouse reports
        if: always() # чтобы грузить даже при warn/fail
        uses: actions/upload-artifact@v4
        with:
          name: lhci-reports
          path: lhci-reports/**
